spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/interviewpartner}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Jitsi: при своём сервере задайте video-meeting.jitsi-base-url
