CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    username VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    language VARCHAR(32),
    level VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_telegram_id UNIQUE (telegram_id)
);

CREATE TABLE interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    format VARCHAR(32) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    duration_minutes INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_interviews_candidate FOREIGN KEY (candidate_id) REFERENCES users (id),
    CONSTRAINT fk_interviews_interviewer FOREIGN KEY (interviewer_id) REFERENCES users (id)
);

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    day_of_week VARCHAR(16) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_available BOOLEAN NOT NULL,
    CONSTRAINT fk_schedules_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP NULL,
    CONSTRAINT fk_notifications_interview FOREIGN KEY (interview_id) REFERENCES interviews (id),
    CONSTRAINT uk_notifications_interview_type UNIQUE (interview_id, type)
);

CREATE INDEX idx_notifications_due ON notifications (sent_at, scheduled_at);

CREATE TABLE interview_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    format VARCHAR(32) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    duration_minutes INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP NULL,
    CONSTRAINT fk_interview_requests_candidate FOREIGN KEY (candidate_id) REFERENCES users (id),
    CONSTRAINT fk_interview_requests_interviewer FOREIGN KEY (interviewer_id) REFERENCES users (id)
);

