ALTER TABLE schedules
    ADD COLUMN language VARCHAR(32) NOT NULL DEFAULT 'JAVA';

CREATE TABLE candidate_slots
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    language     VARCHAR(32)  NOT NULL,
    day_of_week  VARCHAR(16)  NOT NULL,
    start_time   TIME         NOT NULL,
    end_time     TIME         NOT NULL,
    is_available BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_candidate_slots_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_candidate_slots_user ON candidate_slots (user_id);
CREATE INDEX idx_candidate_slots_lang ON candidate_slots (language);
CREATE INDEX idx_schedules_lang ON schedules (language);
