-- Объявления для массовой рассылки в Telegram (текст правьте в БД до отправки).
-- Условие отправки: enabled = true, sent_at IS NULL, scheduled_at <= now (проверка по расписанию приложения).
CREATE TABLE broadcast_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_text TEXT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_broadcast_announcements_due
    ON broadcast_announcements (enabled, sent_at, scheduled_at);

-- Примеры (выполняйте вручную в Adminer/psql), время — как у сервера БД:
--
-- INSERT INTO broadcast_announcements (message_text, scheduled_at, enabled)
-- VALUES ('Текст для всех пользователей', TIMESTAMP '2026-04-09 10:00:00', TRUE);
--
-- UPDATE broadcast_announcements SET message_text = 'Новый текст', scheduled_at = TIMESTAMP '2026-04-09 11:00:00'
-- WHERE id = 1 AND sent_at IS NULL;
--
-- UPDATE broadcast_announcements SET enabled = FALSE WHERE id = 1 AND sent_at IS NULL;


--Новое — новая строка (INSERT), а не правка уже отправленной:

--INSERT INTO broadcast_announcements (message_text, scheduled_at, enabled)
--VALUES ('Напоминание: заполните расписание на неделю.', CURRENT_TIMESTAMP, TRUE);
--CURRENT_TIMESTAMP — «отправить при ближайшей проверке (в пределах ~1 минуты)».
